#include<iostream.h>
#include<coino.h>
class employee()
{
   int eid;
   char ename[10],dept[10];
   float salary;
   employee();
   {
	clrscr();
	cout<<"enter employee id:";
	cin>>id;
	cout<<"enter employee name:";
	cin>>name;
	cout<<"enter employee dept:";
	cin>>dept;
	cout<<"enter employee salary:":
	cin>>salary;
	cout<<"id:"<<eid<<"\n name:"<<ename<<"\n department:"<<dept<<"\n salary:"<<salary<<
    }
};
void main()
{
	employee e1;
	employee e2;
	employee e3:
	employee e4;
	employee e5;
	clrscr();
	getch();
}
